---
version: "2"
run:
  go: "1.26"
linters:
  default: all
  disable:
    - cyclop # already using gocyclo, and its good enough!
    - depguard
    - exhaustruct
    - paralleltest
    - perfsprint
    - varnamelen
    - wrapcheck
    - wsl # deprecated, wsl_v5 included in all ofc
  settings:
    funlen:
      lines: 150
      statements: 50
    gocritic:
      disabled-checks:
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    importas:
      alias:
        - pkg: github.com/carlmontanari/boxen/boxen
          alias: boxen
        - pkg: github.com/carlmontanari/boxen/(\w+)
          alias: boxen$1
        - pkg: github.com/scrapli/scrapligo/v2/(\w+)
          alias: scrapligo$1
      no-unaliased: true
    lll:
      line-length: 100
      tab-width: 4
    staticcheck:
      checks:
        - -ST1000
  exclusions:
    rules:
      - linters:
          - revive
        text: package-comments
      - linters:
          - revive
        path: constants/boxen.go
        text: exported const
      - linters:
          - revive
        path: constants/containerlab.go
        text: exported const
      - linters:
          - revive
        path: constants/flags.go
        text: exported const
      - linters:
          - revive
        path: constants/env.go
        text: exported const
      - linters:
          - goconst
          - gocognit
        path: _test\.go
    warn-unused: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
