name = "boxen"
compatibility_date = "2026-10-01"
workers_dev = true
preview_urls = true
routes = [{ pattern = "boxen.containerlab.dev", custom_domain = true }]

[assets]
directory = "./site"
html_handling = "force-trailing-slash"
not_found_handling = "404-page"
