package agent

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"strings"

	boxenconstants "github.com/carlmontanari/boxen/constants"
	boxenerrors "github.com/carlmontanari/boxen/errors"
	"github.com/google/uuid"
)

const instanceStatePermissions = 0o644

// runPrepareDisk creates the qcow2 overlay the VM writes to, backed by the packaged disk. The
// packaged disk stays untouched in the image layer, so starting a container does not copy the
// whole disk into the container layer. A restarted container keeps using its existing overlay,
// and so keeps the guest's changes.
func (a *Agent) runPrepareDisk(ctx context.Context) error {
	_, err := os.Stat(boxenconstants.RunDiskFilename)
	if err == nil {
		a.l.Info("reusing disk overlay from a previous start", "disk",
			boxenconstants.RunDiskFilename)

		return nil
	}

	if !errors.Is(err, fs.ErrNotExist) {
		return err
	}

	a.l.Info(
		"creating disk overlay",
		"disk", boxenconstants.RunDiskFilename,
		"backingDisk", boxenconstants.DiskFilename,
	)

	// create under a temporary name so an interrupted create is not reused on the next start
	tmpDisk := boxenconstants.RunDiskFilename + ".tmp"

	out, err := exec.CommandContext( //nolint: gosec
		ctx,
		qemuImgBinary,
		"create",
		"-q",
		"-f", "qcow2",
		"-F", "qcow2",
		"-b", boxenconstants.DiskFilename,
		tmpDisk,
	).CombinedOutput()
	if err != nil {
		_ = os.Remove(tmpDisk)

		return fmt.Errorf(
			"%w: failed creating disk overlay: %w: %s",
			boxenerrors.ErrBoxen,
			err,
			strings.TrimSpace(string(out)),
		)
	}

	return os.Rename(tmpDisk, boxenconstants.RunDiskFilename)
}

// runResolveInstanceUUID sets the VM system UUID: UUID from the environment when set, otherwise
// the UUID generated by a previous start of this container, otherwise a new one that is stored
// for the next start. Stable UUIDs keep guest serial numbers and UUID bound licenses intact.
func (a *Agent) runResolveInstanceUUID() error {
	envUUID := os.Getenv(boxenconstants.EnvClabUUID)
	if envUUID != "" {
		parsed, err := uuid.Parse(envUUID)
		if err != nil {
			return fmt.Errorf(
				"%w: invalid %s value %q: %w",
				boxenerrors.ErrBoxen,
				boxenconstants.EnvClabUUID,
				envUUID,
				err,
			)
		}

		a.p.InstanceUUID = parsed.String()

		return nil
	}

	b, err := os.ReadFile(boxenconstants.InstanceUUIDFilename)
	if err == nil {
		parsed, parseErr := uuid.Parse(strings.TrimSpace(string(b)))
		if parseErr == nil {
			a.p.InstanceUUID = parsed.String()

			return nil
		}

		a.l.Warn("ignoring invalid stored instance uuid", "error", parseErr.Error())
	} else if !errors.Is(err, fs.ErrNotExist) {
		return err
	}

	a.p.InstanceUUID = uuid.NewString()

	return os.WriteFile(
		boxenconstants.InstanceUUIDFilename,
		[]byte(a.p.InstanceUUID+"\n"),
		instanceStatePermissions,
	)
}
