// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/v1/server.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BoxenService_Logger_FullMethodName  = "/proto.v1.BoxenService/Logger"
	BoxenService_Builder_FullMethodName = "/proto.v1.BoxenService/Builder"
	BoxenService_Filer_FullMethodName   = "/proto.v1.BoxenService/Filer"
)

// BoxenServiceClient is the client API for BoxenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BoxenServiceClient interface {
	Logger(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LoggerRequest, LoggerResponse], error)
	Builder(ctx context.Context, in *BuilderRequest, opts ...grpc.CallOption) (*BuilderResponse, error)
	Filer(ctx context.Context, in *FilerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FilerResponse], error)
}

type boxenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBoxenServiceClient(cc grpc.ClientConnInterface) BoxenServiceClient {
	return &boxenServiceClient{cc}
}

func (c *boxenServiceClient) Logger(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LoggerRequest, LoggerResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BoxenService_ServiceDesc.Streams[0], BoxenService_Logger_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LoggerRequest, LoggerResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BoxenService_LoggerClient = grpc.ClientStreamingClient[LoggerRequest, LoggerResponse]

func (c *boxenServiceClient) Builder(ctx context.Context, in *BuilderRequest, opts ...grpc.CallOption) (*BuilderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuilderResponse)
	err := c.cc.Invoke(ctx, BoxenService_Builder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxenServiceClient) Filer(ctx context.Context, in *FilerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FilerResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BoxenService_ServiceDesc.Streams[1], BoxenService_Filer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FilerRequest, FilerResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BoxenService_FilerClient = grpc.ServerStreamingClient[FilerResponse]

// BoxenServiceServer is the server API for BoxenService service.
// All implementations must embed UnimplementedBoxenServiceServer
// for forward compatibility.
type BoxenServiceServer interface {
	Logger(grpc.ClientStreamingServer[LoggerRequest, LoggerResponse]) error
	Builder(context.Context, *BuilderRequest) (*BuilderResponse, error)
	Filer(*FilerRequest, grpc.ServerStreamingServer[FilerResponse]) error
	mustEmbedUnimplementedBoxenServiceServer()
}

// UnimplementedBoxenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBoxenServiceServer struct{}

func (UnimplementedBoxenServiceServer) Logger(grpc.ClientStreamingServer[LoggerRequest, LoggerResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Logger not implemented")
}
func (UnimplementedBoxenServiceServer) Builder(context.Context, *BuilderRequest) (*BuilderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Builder not implemented")
}
func (UnimplementedBoxenServiceServer) Filer(*FilerRequest, grpc.ServerStreamingServer[FilerResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Filer not implemented")
}
func (UnimplementedBoxenServiceServer) mustEmbedUnimplementedBoxenServiceServer() {}
func (UnimplementedBoxenServiceServer) testEmbeddedByValue()                      {}

// UnsafeBoxenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BoxenServiceServer will
// result in compilation errors.
type UnsafeBoxenServiceServer interface {
	mustEmbedUnimplementedBoxenServiceServer()
}

func RegisterBoxenServiceServer(s grpc.ServiceRegistrar, srv BoxenServiceServer) {
	// If the following call pancis, it indicates UnimplementedBoxenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BoxenService_ServiceDesc, srv)
}

func _BoxenService_Logger_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BoxenServiceServer).Logger(&grpc.GenericServerStream[LoggerRequest, LoggerResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BoxenService_LoggerServer = grpc.ClientStreamingServer[LoggerRequest, LoggerResponse]

func _BoxenService_Builder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuilderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxenServiceServer).Builder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxenService_Builder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxenServiceServer).Builder(ctx, req.(*BuilderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxenService_Filer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FilerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BoxenServiceServer).Filer(m, &grpc.GenericServerStream[FilerRequest, FilerResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BoxenService_FilerServer = grpc.ServerStreamingServer[FilerResponse]

// BoxenService_ServiceDesc is the grpc.ServiceDesc for BoxenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BoxenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v1.BoxenService",
	HandlerType: (*BoxenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Builder",
			Handler:    _BoxenService_Builder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Logger",
			Handler:       _BoxenService_Logger_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Filer",
			Handler:       _BoxenService_Filer_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/v1/server.proto",
}
