// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v6.33.1
// source: proto/v1/server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Loger RPC
type LoggerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level   string            `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Message string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Fields  map[string]string `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *LoggerRequest) Reset() {
	*x = LoggerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggerRequest) ProtoMessage() {}

func (x *LoggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggerRequest.ProtoReflect.Descriptor instead.
func (*LoggerRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_server_proto_rawDescGZIP(), []int{0}
}

func (x *LoggerRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LoggerRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoggerRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type LoggerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoggerResponse) Reset() {
	*x = LoggerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggerResponse) ProtoMessage() {}

func (x *LoggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggerResponse.ProtoReflect.Descriptor instead.
func (*LoggerResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_server_proto_rawDescGZIP(), []int{1}
}

// Builder RPC
type BuilderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*BuilderRequest_PackageInfoRequest
	//	*BuilderRequest_PackageCompleteRequest
	Request isBuilderRequest_Request `protobuf_oneof:"request"`
}

func (x *BuilderRequest) Reset() {
	*x = BuilderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuilderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuilderRequest) ProtoMessage() {}

func (x *BuilderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuilderRequest.ProtoReflect.Descriptor instead.
func (*BuilderRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_server_proto_rawDescGZIP(), []int{2}
}

func (m *BuilderRequest) GetRequest() isBuilderRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *BuilderRequest) GetPackageInfoRequest() *PackageInfoRequest {
	if x, ok := x.GetRequest().(*BuilderRequest_PackageInfoRequest); ok {
		return x.PackageInfoRequest
	}
	return nil
}

func (x *BuilderRequest) GetPackageCompleteRequest() *PackageCompleteRequest {
	if x, ok := x.GetRequest().(*BuilderRequest_PackageCompleteRequest); ok {
		return x.PackageCompleteRequest
	}
	return nil
}

type isBuilderRequest_Request interface {
	isBuilderRequest_Request()
}

type BuilderRequest_PackageInfoRequest struct {
	PackageInfoRequest *PackageInfoRequest `protobuf:"bytes,1,opt,name=package_info_request,json=packageInfoRequest,proto3,oneof"`
}

type BuilderRequest_PackageCompleteRequest struct {
	PackageCompleteRequest *PackageCompleteRequest `protobuf:"bytes,2,opt,name=package_complete_request,json=packageCompleteRequest,proto3,oneof"`
}

func (*BuilderRequest_PackageInfoRequest) isBuilderRequest_Request() {}

func (*BuilderRequest_PackageCompleteRequest) isBuilderRequest_Request() {}

type PackageInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PackageInfoRequest) Reset() {
	*x = PackageInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageInfoRequest) ProtoMessage() {}

func (x *PackageInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageInfoRequest.ProtoReflect.Descriptor instead.
func (*PackageInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_server_proto_rawDescGZIP(), []int{3}
}

type PackageCompleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PackageCompleteRequest) Reset() {
	*x = PackageCompleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageCompleteRequest) ProtoMessage() {}

func (x *PackageCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageCompleteRequest.ProtoReflect.Descriptor instead.
func (*PackageCompleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_server_proto_rawDescGZIP(), []int{4}
}

type BuilderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*BuilderResponse_PackageInfoResponse
	//	*BuilderResponse_PackageCompleteResponse
	Response isBuilderResponse_Response `protobuf_oneof:"response"`
}

func (x *BuilderResponse) Reset() {
	*x = BuilderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuilderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuilderResponse) ProtoMessage() {}

func (x *BuilderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuilderResponse.ProtoReflect.Descriptor instead.
func (*BuilderResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_server_proto_rawDescGZIP(), []int{5}
}

func (m *BuilderResponse) GetResponse() isBuilderResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *BuilderResponse) GetPackageInfoResponse() *PackageInfoResponse {
	if x, ok := x.GetResponse().(*BuilderResponse_PackageInfoResponse); ok {
		return x.PackageInfoResponse
	}
	return nil
}

func (x *BuilderResponse) GetPackageCompleteResponse() *PackageCompleteResponse {
	if x, ok := x.GetResponse().(*BuilderResponse_PackageCompleteResponse); ok {
		return x.PackageCompleteResponse
	}
	return nil
}

type isBuilderResponse_Response interface {
	isBuilderResponse_Response()
}

type BuilderResponse_PackageInfoResponse struct {
	PackageInfoResponse *PackageInfoResponse `protobuf:"bytes,1,opt,name=package_info_response,json=packageInfoResponse,proto3,oneof"`
}

type BuilderResponse_PackageCompleteResponse struct {
	PackageCompleteResponse *PackageCompleteResponse `protobuf:"bytes,2,opt,name=package_complete_response,json=packageCompleteResponse,proto3,oneof"`
}

func (*BuilderResponse_PackageInfoResponse) isBuilderResponse_Response() {}

func (*BuilderResponse_PackageCompleteResponse) isBuilderResponse_Response() {}

type PackageInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profile []byte `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Disk    string `protobuf:"bytes,2,opt,name=disk,proto3" json:"disk,omitempty"`
}

func (x *PackageInfoResponse) Reset() {
	*x = PackageInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageInfoResponse) ProtoMessage() {}

func (x *PackageInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageInfoResponse.ProtoReflect.Descriptor instead.
func (*PackageInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_server_proto_rawDescGZIP(), []int{6}
}

func (x *PackageInfoResponse) GetProfile() []byte {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *PackageInfoResponse) GetDisk() string {
	if x != nil {
		return x.Disk
	}
	return ""
}

type PackageCompleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PackageCompleteResponse) Reset() {
	*x = PackageCompleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageCompleteResponse) ProtoMessage() {}

func (x *PackageCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageCompleteResponse.ProtoReflect.Descriptor instead.
func (*PackageCompleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_server_proto_rawDescGZIP(), []int{7}
}

// Filer RPC
type FilerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *FilerRequest) Reset() {
	*x = FilerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilerRequest) ProtoMessage() {}

func (x *FilerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilerRequest.ProtoReflect.Descriptor instead.
func (*FilerRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_server_proto_rawDescGZIP(), []int{8}
}

func (x *FilerRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

type FilerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Done bool   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
}

func (x *FilerResponse) Reset() {
	*x = FilerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilerResponse) ProtoMessage() {}

func (x *FilerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilerResponse.ProtoReflect.Descriptor instead.
func (*FilerResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_server_proto_rawDescGZIP(), []int{9}
}

func (x *FilerResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FilerResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_proto_v1_server_proto protoreflect.FileDescriptor

var file_proto_v1_server_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76,
	0x31, 0x22, 0xb7, 0x01, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x6f, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x1a, 0x39, 0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x10, 0x0a, 0x0e, 0x4c,
	0x6f, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xcb, 0x01,
	0x0a, 0x0e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x50, 0x0a, 0x14, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x12,
	0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x5c, 0x0a, 0x18, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x16, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x50,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x18, 0x0a, 0x16, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xd3, 0x01, 0x0a, 0x0f,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x53, 0x0a, 0x15, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x13, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x19, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f,
	0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x17, 0x70, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x43, 0x0a, 0x13, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x69, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x69, 0x73, 0x6b, 0x22, 0x19, 0x0a, 0x17, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x22, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x37, 0x0a, 0x0d, 0x46, 0x69, 0x6c, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f,
	0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x32, 0xc9,
	0x01, 0x0a, 0x0c, 0x42, 0x6f, 0x78, 0x65, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3d, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f,
	0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x3e,
	0x0a, 0x07, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42,
	0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a,
	0x0a, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69,
	0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x61, 0x72, 0x6c, 0x6d, 0x6f, 0x6e,
	0x74, 0x61, 0x6e, 0x61, 0x72, 0x69, 0x2f, 0x62, 0x6f, 0x78, 0x65, 0x6e, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_v1_server_proto_rawDescOnce sync.Once
	file_proto_v1_server_proto_rawDescData = file_proto_v1_server_proto_rawDesc
)

func file_proto_v1_server_proto_rawDescGZIP() []byte {
	file_proto_v1_server_proto_rawDescOnce.Do(func() {
		file_proto_v1_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v1_server_proto_rawDescData)
	})
	return file_proto_v1_server_proto_rawDescData
}

var file_proto_v1_server_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_v1_server_proto_goTypes = []any{
	(*LoggerRequest)(nil),           // 0: proto.v1.LoggerRequest
	(*LoggerResponse)(nil),          // 1: proto.v1.LoggerResponse
	(*BuilderRequest)(nil),          // 2: proto.v1.BuilderRequest
	(*PackageInfoRequest)(nil),      // 3: proto.v1.PackageInfoRequest
	(*PackageCompleteRequest)(nil),  // 4: proto.v1.PackageCompleteRequest
	(*BuilderResponse)(nil),         // 5: proto.v1.BuilderResponse
	(*PackageInfoResponse)(nil),     // 6: proto.v1.PackageInfoResponse
	(*PackageCompleteResponse)(nil), // 7: proto.v1.PackageCompleteResponse
	(*FilerRequest)(nil),            // 8: proto.v1.FilerRequest
	(*FilerResponse)(nil),           // 9: proto.v1.FilerResponse
	nil,                             // 10: proto.v1.LoggerRequest.FieldsEntry
}
var file_proto_v1_server_proto_depIdxs = []int32{
	10, // 0: proto.v1.LoggerRequest.fields:type_name -> proto.v1.LoggerRequest.FieldsEntry
	3,  // 1: proto.v1.BuilderRequest.package_info_request:type_name -> proto.v1.PackageInfoRequest
	4,  // 2: proto.v1.BuilderRequest.package_complete_request:type_name -> proto.v1.PackageCompleteRequest
	6,  // 3: proto.v1.BuilderResponse.package_info_response:type_name -> proto.v1.PackageInfoResponse
	7,  // 4: proto.v1.BuilderResponse.package_complete_response:type_name -> proto.v1.PackageCompleteResponse
	0,  // 5: proto.v1.BoxenService.Logger:input_type -> proto.v1.LoggerRequest
	2,  // 6: proto.v1.BoxenService.Builder:input_type -> proto.v1.BuilderRequest
	8,  // 7: proto.v1.BoxenService.Filer:input_type -> proto.v1.FilerRequest
	1,  // 8: proto.v1.BoxenService.Logger:output_type -> proto.v1.LoggerResponse
	5,  // 9: proto.v1.BoxenService.Builder:output_type -> proto.v1.BuilderResponse
	9,  // 10: proto.v1.BoxenService.Filer:output_type -> proto.v1.FilerResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_v1_server_proto_init() }
func file_proto_v1_server_proto_init() {
	if File_proto_v1_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_v1_server_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*LoggerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_server_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*LoggerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_server_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*BuilderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_server_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*PackageInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_server_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*PackageCompleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_server_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*BuilderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_server_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*PackageInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_server_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*PackageCompleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_server_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*FilerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_server_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*FilerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_v1_server_proto_msgTypes[2].OneofWrappers = []any{
		(*BuilderRequest_PackageInfoRequest)(nil),
		(*BuilderRequest_PackageCompleteRequest)(nil),
	}
	file_proto_v1_server_proto_msgTypes[5].OneofWrappers = []any{
		(*BuilderResponse_PackageInfoResponse)(nil),
		(*BuilderResponse_PackageCompleteResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v1_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_server_proto_goTypes,
		DependencyIndexes: file_proto_v1_server_proto_depIdxs,
		MessageInfos:      file_proto_v1_server_proto_msgTypes,
	}.Build()
	File_proto_v1_server_proto = out.File
	file_proto_v1_server_proto_rawDesc = nil
	file_proto_v1_server_proto_goTypes = nil
	file_proto_v1_server_proto_depIdxs = nil
}
