---
name: Commit

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: ["1.18"]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up go ${{ matrix.version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.version }}
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45
